// Single source of truth for the genre/vibe options shown in the UI and used
// when seeding. Keeping it here avoids an extra round-trip just to list chips.

export type Mode = "MUSIC" | "MOVIE" | "BOOK";

export const TAXONOMY = {
  MUSIC: {
    genres: [
      "Pop", "Indie", "Hip-Hop", "R&B", "Rock", "Metal", "Punk", "Electronic",
      "Lo-fi", "Jazz", "Blues", "Soul", "Funk", "Reggae", "Country", "Folk",
      "Latin", "K-Pop", "Classical",
    ],
    vibes: ["Chill", "Energetic", "Sad", "Focus", "Party", "Romantic"],
  },
  MOVIE: {
    types: ["movie", "series"] as const,
    genres: [
      "Action", "Adventure", "Comedy", "Thriller", "Drama", "Sci-Fi", "Fantasy",
      "Horror", "Mystery", "Crime", "Romance", "Animation", "Anime", "Family",
      "Documentary", "History", "War", "Western",
    ],
    vibes: ["Feel-good", "Edge-of-seat", "Cozy", "Mind-bending", "Tear-jerker"],
  },
  BOOK: {
    genres: [
      "Fiction", "Mystery", "Sci-Fi", "Fantasy", "Romance", "Thriller", "Horror",
      "Historical", "Adventure", "Young Adult", "Classics", "Poetry",
      "Graphic Novel", "Non-fiction", "Biography", "Self-help",
    ],
    vibes: ["Cozy", "Page-turner", "Thought-provoking", "Heartwarming", "Dark"],
  },
} as const;

/** Decade filter (start year → that decade), newest first. Applies to every mode. */
export const DECADES: { label: string; value: number }[] = [
  { label: "2020s", value: 2020 },
  { label: "2010s", value: 2010 },
  { label: "2000s", value: 2000 },
  { label: "90s", value: 1990 },
  { label: "80s", value: 1980 },
  { label: "70s", value: 1970 },
  { label: "60s", value: 1960 },
  { label: "50s", value: 1950 },
  { label: "40s", value: 1940 },
];

/**
 * Country filter. `code` is an ISO 3166-1 alpha-2 country code used as TMDB's
 * origin-country (movies/series) and Spotify's market (music); the optional `lang`
 * is the MARC language code used to bias Open Library results (books). Applies to
 * all modes, best-effort per the catalogue's capabilities. Countries without an
 * explicit `lang` default to English (see `countryLang`); a code the live
 * providers don't recognise degrades gracefully to the unfiltered pool.
 */
export const COUNTRIES: { label: string; code: string; lang?: string }[] = [
  { label: "Afghanistan", code: "AF" },
  { label: "Albania", code: "AL" },
  { label: "Algeria", code: "DZ" },
  { label: "Andorra", code: "AD" },
  { label: "Angola", code: "AO" },
  { label: "Antigua and Barbuda", code: "AG" },
  { label: "Argentina", code: "AR", lang: "spa" },
  { label: "Armenia", code: "AM" },
  { label: "Australia", code: "AU", lang: "eng" },
  { label: "Austria", code: "AT", lang: "ger" },
  { label: "Azerbaijan", code: "AZ" },
  { label: "Bahamas", code: "BS" },
  { label: "Bahrain", code: "BH" },
  { label: "Bangladesh", code: "BD" },
  { label: "Barbados", code: "BB" },
  { label: "Belarus", code: "BY" },
  { label: "Belgium", code: "BE" },
  { label: "Belize", code: "BZ" },
  { label: "Benin", code: "BJ" },
  { label: "Bhutan", code: "BT" },
  { label: "Bolivia", code: "BO", lang: "spa" },
  { label: "Bosnia and Herzegovina", code: "BA" },
  { label: "Botswana", code: "BW" },
  { label: "Brazil", code: "BR", lang: "por" },
  { label: "Brunei", code: "BN" },
  { label: "Bulgaria", code: "BG" },
  { label: "Burkina Faso", code: "BF" },
  { label: "Burundi", code: "BI" },
  { label: "Cambodia", code: "KH" },
  { label: "Cameroon", code: "CM" },
  { label: "Canada", code: "CA", lang: "eng" },
  { label: "Cape Verde", code: "CV" },
  { label: "Central African Republic", code: "CF" },
  { label: "Chad", code: "TD" },
  { label: "Chile", code: "CL", lang: "spa" },
  { label: "China", code: "CN", lang: "chi" },
  { label: "Colombia", code: "CO", lang: "spa" },
  { label: "Comoros", code: "KM" },
  { label: "Congo (Brazzaville)", code: "CG" },
  { label: "Congo (Kinshasa)", code: "CD" },
  { label: "Costa Rica", code: "CR", lang: "spa" },
  { label: "Côte d'Ivoire", code: "CI" },
  { label: "Croatia", code: "HR" },
  { label: "Cuba", code: "CU", lang: "spa" },
  { label: "Cyprus", code: "CY" },
  { label: "Czechia", code: "CZ" },
  { label: "Denmark", code: "DK", lang: "dan" },
  { label: "Djibouti", code: "DJ" },
  { label: "Dominica", code: "DM" },
  { label: "Dominican Republic", code: "DO", lang: "spa" },
  { label: "Ecuador", code: "EC", lang: "spa" },
  { label: "Egypt", code: "EG", lang: "ara" },
  { label: "El Salvador", code: "SV", lang: "spa" },
  { label: "Equatorial Guinea", code: "GQ" },
  { label: "Eritrea", code: "ER" },
  { label: "Estonia", code: "EE" },
  { label: "Eswatini", code: "SZ" },
  { label: "Ethiopia", code: "ET" },
  { label: "Fiji", code: "FJ" },
  { label: "Finland", code: "FI", lang: "fin" },
  { label: "France", code: "FR", lang: "fre" },
  { label: "Gabon", code: "GA" },
  { label: "Gambia", code: "GM" },
  { label: "Georgia", code: "GE" },
  { label: "Germany", code: "DE", lang: "ger" },
  { label: "Ghana", code: "GH" },
  { label: "Greece", code: "GR", lang: "gre" },
  { label: "Grenada", code: "GD" },
  { label: "Guatemala", code: "GT", lang: "spa" },
  { label: "Guinea", code: "GN" },
  { label: "Guinea-Bissau", code: "GW" },
  { label: "Guyana", code: "GY" },
  { label: "Haiti", code: "HT" },
  { label: "Honduras", code: "HN", lang: "spa" },
  { label: "Hong Kong", code: "HK", lang: "chi" },
  { label: "Hungary", code: "HU", lang: "hun" },
  { label: "Iceland", code: "IS", lang: "ice" },
  { label: "India", code: "IN", lang: "eng" },
  { label: "Indonesia", code: "ID", lang: "ind" },
  { label: "Iran", code: "IR", lang: "per" },
  { label: "Iraq", code: "IQ", lang: "ara" },
  { label: "Ireland", code: "IE", lang: "eng" },
  { label: "Israel", code: "IL", lang: "heb" },
  { label: "Italy", code: "IT", lang: "ita" },
  { label: "Jamaica", code: "JM" },
  { label: "Japan", code: "JP", lang: "jpn" },
  { label: "Jordan", code: "JO", lang: "ara" },
  { label: "Kazakhstan", code: "KZ" },
  { label: "Kenya", code: "KE" },
  { label: "Kiribati", code: "KI" },
  { label: "Kuwait", code: "KW", lang: "ara" },
  { label: "Kyrgyzstan", code: "KG" },
  { label: "Laos", code: "LA" },
  { label: "Latvia", code: "LV" },
  { label: "Lebanon", code: "LB", lang: "ara" },
  { label: "Lesotho", code: "LS" },
  { label: "Liberia", code: "LR" },
  { label: "Libya", code: "LY", lang: "ara" },
  { label: "Liechtenstein", code: "LI" },
  { label: "Lithuania", code: "LT" },
  { label: "Luxembourg", code: "LU" },
  { label: "Madagascar", code: "MG" },
  { label: "Malawi", code: "MW" },
  { label: "Malaysia", code: "MY" },
  { label: "Maldives", code: "MV" },
  { label: "Mali", code: "ML" },
  { label: "Malta", code: "MT" },
  { label: "Marshall Islands", code: "MH" },
  { label: "Mauritania", code: "MR" },
  { label: "Mauritius", code: "MU" },
  { label: "Mexico", code: "MX", lang: "spa" },
  { label: "Micronesia", code: "FM" },
  { label: "Moldova", code: "MD" },
  { label: "Monaco", code: "MC" },
  { label: "Mongolia", code: "MN" },
  { label: "Montenegro", code: "ME" },
  { label: "Morocco", code: "MA", lang: "ara" },
  { label: "Mozambique", code: "MZ", lang: "por" },
  { label: "Myanmar", code: "MM" },
  { label: "Namibia", code: "NA" },
  { label: "Nauru", code: "NR" },
  { label: "Nepal", code: "NP" },
  { label: "Netherlands", code: "NL", lang: "dut" },
  { label: "New Zealand", code: "NZ", lang: "eng" },
  { label: "Nicaragua", code: "NI", lang: "spa" },
  { label: "Niger", code: "NE" },
  { label: "Nigeria", code: "NG", lang: "eng" },
  { label: "North Korea", code: "KP", lang: "kor" },
  { label: "North Macedonia", code: "MK" },
  { label: "Norway", code: "NO", lang: "nor" },
  { label: "Oman", code: "OM", lang: "ara" },
  { label: "Pakistan", code: "PK" },
  { label: "Palau", code: "PW" },
  { label: "Palestine", code: "PS", lang: "ara" },
  { label: "Panama", code: "PA", lang: "spa" },
  { label: "Papua New Guinea", code: "PG" },
  { label: "Paraguay", code: "PY", lang: "spa" },
  { label: "Peru", code: "PE", lang: "spa" },
  { label: "Philippines", code: "PH" },
  { label: "Poland", code: "PL", lang: "pol" },
  { label: "Portugal", code: "PT", lang: "por" },
  { label: "Qatar", code: "QA", lang: "ara" },
  { label: "Romania", code: "RO", lang: "rum" },
  { label: "Russia", code: "RU", lang: "rus" },
  { label: "Rwanda", code: "RW" },
  { label: "Saint Kitts and Nevis", code: "KN" },
  { label: "Saint Lucia", code: "LC" },
  { label: "Saint Vincent and the Grenadines", code: "VC" },
  { label: "Samoa", code: "WS" },
  { label: "San Marino", code: "SM" },
  { label: "São Tomé and Príncipe", code: "ST" },
  { label: "Saudi Arabia", code: "SA", lang: "ara" },
  { label: "Senegal", code: "SN" },
  { label: "Serbia", code: "RS" },
  { label: "Seychelles", code: "SC" },
  { label: "Sierra Leone", code: "SL" },
  { label: "Singapore", code: "SG" },
  { label: "Slovakia", code: "SK" },
  { label: "Slovenia", code: "SI" },
  { label: "Solomon Islands", code: "SB" },
  { label: "Somalia", code: "SO" },
  { label: "South Africa", code: "ZA", lang: "eng" },
  { label: "South Korea", code: "KR", lang: "kor" },
  { label: "South Sudan", code: "SS" },
  { label: "Spain", code: "ES", lang: "spa" },
  { label: "Sri Lanka", code: "LK" },
  { label: "Sudan", code: "SD", lang: "ara" },
  { label: "Suriname", code: "SR" },
  { label: "Sweden", code: "SE", lang: "swe" },
  { label: "Switzerland", code: "CH", lang: "ger" },
  { label: "Syria", code: "SY", lang: "ara" },
  { label: "Taiwan", code: "TW", lang: "chi" },
  { label: "Tajikistan", code: "TJ" },
  { label: "Tanzania", code: "TZ" },
  { label: "Thailand", code: "TH", lang: "tha" },
  { label: "Timor-Leste", code: "TL" },
  { label: "Togo", code: "TG" },
  { label: "Tonga", code: "TO" },
  { label: "Trinidad and Tobago", code: "TT" },
  { label: "Tunisia", code: "TN", lang: "ara" },
  { label: "Turkey", code: "TR", lang: "tur" },
  { label: "Turkmenistan", code: "TM" },
  { label: "Tuvalu", code: "TV" },
  { label: "Uganda", code: "UG" },
  { label: "Ukraine", code: "UA", lang: "ukr" },
  { label: "United Arab Emirates", code: "AE", lang: "ara" },
  { label: "United Kingdom", code: "GB", lang: "eng" },
  { label: "United States", code: "US", lang: "eng" },
  { label: "Uruguay", code: "UY", lang: "spa" },
  { label: "Uzbekistan", code: "UZ" },
  { label: "Vanuatu", code: "VU" },
  { label: "Vatican City", code: "VA" },
  { label: "Venezuela", code: "VE", lang: "spa" },
  { label: "Vietnam", code: "VN", lang: "vie" },
  { label: "Yemen", code: "YE", lang: "ara" },
  { label: "Zambia", code: "ZM" },
  { label: "Zimbabwe", code: "ZW" },
];

/** MARC language code for a country (books); defaults to English. */
export const countryLang = (code?: string | null): string => COUNTRIES.find((c) => c.code === code)?.lang ?? "eng";

/**
 * Minimum-rating filter, per mode and on each mode's native scale: movies/series
 * use TMDB's 0–10 vote average, books use Open Library's 0–5 average. Music has
 * no rating, so it offers none.
 */
export const RATINGS: Record<Mode, { label: string; value: number }[]> = {
  MUSIC: [],
  MOVIE: [
    { label: "6+", value: 6 },
    { label: "7+", value: 7 },
    { label: "8+", value: 8 },
  ],
  BOOK: [
    { label: "3+", value: 3 },
    { label: "4+", value: 4 },
    { label: "4.5+", value: 4.5 },
  ],
};

export const MODE_META: Record<Mode, { label: string; greeting: string }> = {
  MUSIC: { label: "Music", greeting: "What to listen to?" },
  MOVIE: { label: "Movies & TV", greeting: "What to watch?" },
  BOOK: { label: "Books", greeting: "What to read?" },
};
